name: Auto Update Mediabay Token

on:
  schedule:
    - cron: '*/30 * * * *'  # Har 30 daqiqada
  workflow_dispatch:  # Qo'lda ishga tushirish

jobs:
  update-token:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Get new token and update Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          WORKER_NAME: ${{ secrets.WORKER_NAME }}
          SITE_LOGIN: ${{ secrets.SITE_LOGIN }}
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
        run: python update_token.py
